/* RV32I tests using Python-assembled programs from rv32i_asm.py.
 * Tests are compiled from .s files via rv32i_asm.py, which outputs
 * uint32_t arrays embedded as C header.  This file includes them
 * and runs each program through the qsim RV32I simulation.
 */
#include "minunit.h"
#include "libqsim/session.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>

/* ================================================================
 * Test programs — generated by rv32i_asm.py
 * ================================================================ */

/* rv32i_test_add.s */
static uint32_t prog_add[] = {
    0x02A00513, /* 0: addi x10, x0, 42 */
    0x00100073, /* 4: ebreak */
};

/* rv32i_test_fib.s — expects x10 = 55 (0x37) */
static uint32_t prog_fib[] = {
    0x00000513, /* 0:  addi x10, x0, 0 */
    0x00100593, /* 4:  addi x11, x0, 1 */
    0x00A00613, /* 8:  addi x12, x0, 10 */
    0x00B506B3, /* 12: add  x13, x10, x11 */
    0x00058513, /* 16: addi x10, x11, 0 */
    0x00068593, /* 20: addi x11, x13, 0 */
    0xFFF60613, /* 24: addi x12, x12, -1 */
    0xFE0618E3, /* 28: bne  x12, x0, loop (-16) */
    0x00100073, /* 32: ebreak */
};

/* rv32i_test_lw_sw.s — expects x10 = 42 */
static uint32_t prog_lw_sw[] = {
    0x02A00513, /* 0:  addi x10, x0, 42  */
    0x000105B7, /* 4:  lui  x11, 0x10 */
    0x00A5A023, /* 8:  sw   x10, 0(x11)  */
    0x00000513, /* 12: addi x10, x0, 0   */
    0x0005A603, /* 16: lw   x12, 0(x11)  */
    0x00060513, /* 20: addi x10, x12, 0  */
    0x00100073, /* 24: ebreak            */
};

/* rv32i_test_branch.s — expects x10=1,x11=1,x12=1,x13=1 */
static uint32_t prog_branch[] = {
    0x00500713, /* 0:   addi x14, x0, 5   */
    0x00500793, /* 4:   addi x15, x0, 5   */
    0x00000513, /* 8:   addi x10, x0, 0   */
    0x00F70463, /* 12:  beq  x14, x15, +8 (should take) */
    0x00000513, /* 16:  addi x10, x0, 0   */
    0x00100513, /* 20:  addi x10, x0, 1   */
    0x00500813, /* 24:  addi x16, x0, 5   */
    0x00600893, /* 28:  addi x17, x0, 6   */
    0x00000593, /* 32:  addi x11, x0, 0   */
    0x01181463, /* 36:  bne  x16, x17, +8 (should take) */
    0x00000593, /* 40:  addi x11, x0, 0   */
    0x00100593, /* 44:  addi x11, x0, 1   */
    0xFFD00913, /* 48:  addi x18, x0, -3  */
    0x00200993, /* 52:  addi x19, x0, 2   */
    0x00000613, /* 56:  addi x12, x0, 0   */
    0x01394463, /* 60:  blt  x18, x19, +8 (should take) */
    0x00000613, /* 64:  addi x12, x0, 0   */
    0x00100613, /* 68:  addi x12, x0, 1   */
    0x00700A13, /* 72:  addi x20, x0, 7   */
    0x00700A93, /* 76:  addi x21, x0, 7   */
    0x00000693, /* 80:  addi x13, x0, 0   */
    0x015A5463, /* 84:  bge  x20, x21, +8 (should take) */
    0x00000693, /* 88:  addi x13, x0, 0   */
    0x00100693, /* 92:  addi x13, x0, 1   */
    0x00100073, /* 96:  ebreak            */
};

/* rv32i_test_jal.s — expects x10 = 42 after JAL+JALR return */
static uint32_t prog_jal[] = {
    0x00C000EF, /* 0:  jal  x1, target (+12) */
    0x00000013, /* 4:  nop      (return target)     */
    0x00100073, /* 8:  ebreak   (not reached)        */
    0x02A00513, /* 12: addi x10, x0, 42  (target)    */
    0x00008067, /* 16: jalr x0, x1, 0   (return)      */
    0x00000013, /* 20: nop      (not reached)        */
};

/* rv32i_test_alu.s — expects x10=10,x11=4,x12=56,x13=0,x14=0,
 *                    x15=4,x16=0,x17=-2,x18=7,x19=3 */
static uint32_t prog_alu[] = {
    0x00700293, /* 0:   addi x5, x0, 7    */
    0x00300313, /* 4:   addi x6, x0, 3    */
    0x00628533, /* 8:   add  x10, x5, x6  */
    0x406285B3, /* 12:  sub  x11, x5, x6  */
    0x00700293, /* 16:  addi x5, x0, 7    */
    0x00300313, /* 20:  addi x6, x0, 3    */
    0x00629633, /* 24:  sll  x12, x5, x6  */
    0x00700293, /* 28:  addi x5, x0, 7    */
    0x00300313, /* 32:  addi x6, x0, 3    */
    0x0062A6B3, /* 36:  slt  x13, x5, x6  */
    0x0062B733, /* 40:  sltu x14, x5, x6  */
    0x0062C7B3, /* 44:  xor  x15, x5, x6  */
    0x00300393, /* 48:  addi x7, x0, 3    */
    0x0072D833, /* 52:  srl  x16, x5, x7  */
    0xFF800413, /* 56:  addi x8, x0, -8   */
    0x00200493, /* 60:  addi x9, x0, 2    */
    0x409458B3, /* 64:  sra  x17, x8, x9  */
    0x0062E933, /* 68:  or   x18, x5, x6  */
    0x0062F9B3, /* 72:  and  x19, x5, x6  */
    0x00100073, /* 76:  ebreak            */
};

static const char *lsbfirst_55 = "11101100000000000000000000000000";  /* 0x37 = 55 */
static const char *lsbfirst_42 = "01010100000000000000000000000000";  /* 0x2A = 42 */
static const char *lsbfirst_10 = "01010000000000000000000000000000";  /* 10 */
static const char *lsbfirst_4  = "00100000000000000000000000000000";  /* 4 */
static const char *lsbfirst_56 = "00011100000000000000000000000000";  /* 56 = 0x38, LSB-first */
static const char *lsbfirst_0  = "00000000000000000000000000000000";
static const char *lsbfirst_1  = "10000000000000000000000000000000";
static const char *lsbfirst_7  = "11100000000000000000000000000000";
static const char *lsbfirst_3  = "11000000000000000000000000000000";
static const char *lsbfirst_m2 = "01111111111111111111111111111111";  /* -2, LSB-first */

/* ================================================================
 * Helpers
 * ================================================================ */

static size_t read_rv32i_verilog(size_t *out_len, char **out) {
    const char *paths[] = {"../../example/rv32i/rv32i_top.v",
                           "../../../example/rv32i/rv32i_top.v",
                           "example/rv32i/rv32i_top.v",
                           "../example/rv32i/rv32i_top.v",
                           "../libqsim/../example/rv32i/rv32i_top.v"};
    FILE *f = NULL;
    for (int i = 0; i < 5; i++) {
        f = fopen(paths[i], "rb");
        if (f) break;
    }
    if (!f) return 0;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *src = malloc((size_t)len + 1);
    if (!src) { fclose(f); return 0; }
    size_t nread = fread(src, 1, (size_t)len, f);
    src[nread] = '\0';
    fclose(f);
    *out = src;
    *out_len = nread;
    return (size_t)len;
}

#define IMEM_WORDS 1024
#define IMEM_BITS (IMEM_WORDS * 32)

static void build_imem_str32(char *out, const uint32_t *program, size_t count) {
    for (int i = 0; i < IMEM_WORDS; i++) {
        uint32_t val = ((size_t)i < count) ? program[i] : 0x00100073;  /* EBREAK */
        for (int b = 0; b < 32; b++) {
            int pos = IMEM_BITS - 1 - (i * 32 + b);
            out[pos] = ((val >> b) & 1) ? '1' : '0';
        }
    }
    out[IMEM_BITS] = '\0';
}

static void session_reset(qsim_session_t *sess) {
    qsim_session_set_str(sess, "rst", "0");
    qsim_session_set_str(sess, "clk", "0");
    qsim_session_step_delta(sess);
    qsim_session_set_str(sess, "rst", "1");
    qsim_session_step_delta(sess);
    qsim_session_set_str(sess, "rst", "0");
    qsim_session_step_delta(sess);
}

static char *session_clock_cycle(qsim_session_t *sess) {
    qsim_session_set_str(sess, "clk", "0");
    qsim_session_step_delta(sess);
    qsim_session_set_str(sess, "clk", "1");
    qsim_session_step_delta(sess);
    return qsim_session_eval_str(sess, "halted");
}

static int run_test(qsim_session_t *sess, const uint32_t *program,
                    size_t count, int max_cycles) {
    char imem_str[IMEM_BITS + 1];
    build_imem_str32(imem_str, program, count);
    int ok = qsim_session_force_str(sess, "imem", imem_str);
    if (!ok) return -1;
    session_reset(sess);
    for (int cycle = 0; cycle < max_cycles; cycle++) {
        char *h = session_clock_cycle(sess);
        if (h && h[0] == '1') { free(h); return cycle; }
        free(h);
    }
    return -2;  /* didn't halt */
}

static qsim_session_t *create_session(void) {
    size_t src_len;
    char *src;
    if (!read_rv32i_verilog(&src_len, &src)) return NULL;
    qsim_session_t *sess = qsim_session_create();
    if (!sess) { free(src); return NULL; }
    int ok = qsim_session_compile_string(sess, "rv32i_top.v", src);
    free(src);
    if (!ok) { qsim_session_free(sess); return NULL; }
    ok = qsim_session_elaborate(sess);
    if (!ok) { qsim_session_free(sess); return NULL; }
    return sess;
}

static int check_reg(qsim_session_t *sess, const char *reg,
                     const char *expected) {
    char *val = qsim_session_eval_str(sess, reg);
    if (!val) return 0;
    int match = strcmp(val, expected) == 0;
    if (!match) {
        printf("    %s: got %s, expected %s\n", reg, val, expected);
    }
    free(val);
    return match;
}

/* ================================================================
 * Tests
 * ================================================================ */

static void test_asm_addi(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_add, 2, 10);
    mu_assert(hc >= 0, "addi: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_42), "x10 = 42");
    qsim_session_free(sess);
}

static void test_asm_fib10(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_fib, 9, 200);
    mu_assert(hc >= 0, "fib: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_55), "x10 = 55");
    qsim_session_free(sess);
}

static void test_asm_lw_sw(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_lw_sw, 7, 30);
    mu_assert(hc >= 0, "lw_sw: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_42), "x10 = 42 (load-back)");
    qsim_session_free(sess);
}

static void test_asm_branch(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_branch, 25, 100);
    mu_assert(hc >= 0, "branch: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_1), "x10 = 1 (BEQ)");
    mu_assert(check_reg(sess, "x11", lsbfirst_1), "x11 = 1 (BNE)");
    mu_assert(check_reg(sess, "x12", lsbfirst_1), "x12 = 1 (BLT)");
    mu_assert(check_reg(sess, "x13", lsbfirst_1), "x13 = 1 (BGE)");
    qsim_session_free(sess);
}

static void test_asm_jal(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_jal, 6, 20);
    mu_assert(hc >= 0, "jal: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_42), "x10 = 42 (JAL+JALR)");
    qsim_session_free(sess);
}

static void test_asm_alu(void) {
    qsim_session_t *sess = create_session();
    mu_assert_not_null(sess);
    int hc = run_test(sess, prog_alu, 20, 40);
    mu_assert(hc >= 0, "alu: didn't halt");
    mu_assert(check_reg(sess, "x10", lsbfirst_10), "x10 = 10 (ADD)");
    mu_assert(check_reg(sess, "x11", lsbfirst_4),  "x11 = 4  (SUB)");
    mu_assert(check_reg(sess, "x12", lsbfirst_56), "x12 = 56 (SLL)");
    mu_assert(check_reg(sess, "x13", lsbfirst_0),  "x13 = 0  (SLT)");
    mu_assert(check_reg(sess, "x14", lsbfirst_0),  "x14 = 0  (SLTU)");
    mu_assert(check_reg(sess, "x15", lsbfirst_4),  "x15 = 4  (XOR)");
    mu_assert(check_reg(sess, "x16", lsbfirst_0),  "x16 = 0  (SRL)");
    mu_assert(check_reg(sess, "x17", lsbfirst_m2), "x17 = -2 (SRA)");
    mu_assert(check_reg(sess, "x18", lsbfirst_7),  "x18 = 7  (OR)");
    mu_assert(check_reg(sess, "x19", lsbfirst_3),  "x19 = 3  (AND)");
    qsim_session_free(sess);
}

/* ================================================================
 * Registration
 * ================================================================ */

void register_rv32i_asm_tests(void) {
    printf("[RV32I ASM]\n");
    mu_run_test(test_asm_addi);
    mu_run_test(test_asm_fib10);
    mu_run_test(test_asm_lw_sw);
    mu_run_test(test_asm_branch);
    mu_run_test(test_asm_jal);
    mu_run_test(test_asm_alu);
    printf("\n");
}
